SELECT "TestTB"."COURSE"."COURSE", "TestTB"."COURSE_TEXTBOOK"."TEXTBOOK", "TestTB"."ADVID_COURSE"."ADVID"
	FROM "TestTB"."COURSE_TEXTBOOK", "TestTB"."ADVID_COURSE", "TestTB"."COURSE"
	WHERE "TestTB"."COURSE"."COURSE" = "TestTB"."ADVID_COURSE"."COURSE"
	AND "TestTB"."COURSE"."COURSE" = "TestTB"."COURSE_TEXTBOOK"."COURSE"
	AND "TestTB"."ADVID_COURSE"."ADVID" = 2